Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -14,20 +14,14 @@ jobs:
         uses: actions/checkout@v2
       - name: Install CMake
         run: sudo apt-get install -y cmake
-      - name: List contents of the directory
-        run: ls -la
-      - name: Verify CMakeLists.txt location
-        run: |
-          ls -la
-          test -e CMakeLists.txt || { echo "CMakeLists.txt not found"; exit 1; }
-      - name: Remove existing build directory
-        run: rm -rf build
-      - name: Create build directory
-        run: mkdir build
       - name: Configure CMake
         run: cmake -S . -B build
       - name: Build
         run: cmake --build build
+      - name: Check for test executable
+        run: |
+          ls -la build/
+          test -e build/CompositeExampleTests || { echo "CompositeExampleTests not found"; exit 1; }
       - name: Run tests
         run: ctest --test-dir build
       - name: Upload build
